"""Portable command service and worker foundation."""

from .application import (
    AuthorizationDenied,
    CommandNotFound,
    CommandService,
    IdempotencyConflict,
    UUIDCommandIdGenerator,
)
from .models import (
    AuditEvent,
    AuditEventType,
    AuthenticatedCommandContext,
    AuthorizationDecision,
    CancellationResult,
    Claim,
    CommandEnvelope,
    CommandLimits,
    CommandRecord,
    CommandRequest,
    CommandStatus,
    JSONValue,
    ProgressUpdate,
    RequestDigest,
    SubmissionDisposition,
    SubmissionResult,
    request_digest,
)
from .ports import (
    AuditSink,
    ClaimStatus,
    Clock,
    CommandAuthorizer,
    CommandIdGenerator,
    CommandRepository,
    Delivery,
    DrainSignal,
    ExecutionContext,
    Executor,
    HeartbeatHandle,
    HeartbeatScheduler,
    LifecycleStore,
    Transport,
)
from .repository import InMemoryCommandRepository
from .scheduler import ThreadHeartbeatScheduler
from .service import (
    CommandWorkerService,
    EventDrainSignal,
    ServiceOutcome,
    ServiceReceiveError,
    ServiceStopReason,
)
from .worker import (
    CancellationRequestedError,
    CommandWorker,
    LeaseLostError,
    ProcessOutcome,
)

__all__ = [
    "AuditEvent",
    "AuditEventType",
    "AuditSink",
    "AuthenticatedCommandContext",
    "AuthorizationDecision",
    "AuthorizationDenied",
    "CancellationResult",
    "CancellationRequestedError",
    "Claim",
    "ClaimStatus",
    "Clock",
    "CommandAuthorizer",
    "CommandEnvelope",
    "CommandIdGenerator",
    "CommandLimits",
    "CommandNotFound",
    "CommandRecord",
    "CommandRepository",
    "CommandRequest",
    "CommandService",
    "CommandStatus",
    "CommandWorker",
    "CommandWorkerService",
    "Delivery",
    "DrainSignal",
    "EventDrainSignal",
    "ExecutionContext",
    "Executor",
    "HeartbeatHandle",
    "HeartbeatScheduler",
    "IdempotencyConflict",
    "InMemoryCommandRepository",
    "JSONValue",
    "LeaseLostError",
    "LifecycleStore",
    "ProcessOutcome",
    "ProgressUpdate",
    "RequestDigest",
    "ServiceOutcome",
    "ServiceReceiveError",
    "ServiceStopReason",
    "SubmissionDisposition",
    "SubmissionResult",
    "ThreadHeartbeatScheduler",
    "Transport",
    "UUIDCommandIdGenerator",
    "request_digest",
]
