[tool.semantic_release]
version_variable = [
    "setup.py:version",
    "plexus/__init__.py:__version__"
]
version_toml = []
version_pattern = []
commit_message = "chore: release {version}"
major_on_zero = false
tag_format = "v{version}"
changelog_file = "CHANGELOG.md"
build_command = ""
starting_version = "0.0.0"
version_source = "tag"

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.branches.staging]
match = "staging"
prerelease = true
prerelease_token = "rc"

[tool.semantic_release.branches.develop]
match = "develop"
prerelease = true
prerelease_token = "alpha" 