// Simple test diagram representing a data pipeline flow
export const testPipelineDiagram = {
  elements: [
    // Data Input box
    {
      id: "data-input",
      type: "rectangle",
      x: 50,
      y: 100,
      width: 120,
      height: 60,
      strokeColor: "#1e1e1e",
      backgroundColor: "#e3f2fd",
      fillStyle: "solid",
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 1,
      version: 1,
      versionNonce: 1,
      isDeleted: false,
    },
    // Data Input label
    {
      id: "data-input-text",
      type: "text",
      x: 75,
      y: 120,
      width: 70,
      height: 20,
      text: "Data Input",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 2,
      version: 1,
      versionNonce: 2,
      isDeleted: false,
    },
    // Arrow 1
    {
      id: "arrow-1",
      type: "arrow",
      x: 170,
      y: 130,
      width: 60,
      height: 0,
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "round",
      seed: 3,
      version: 1,
      versionNonce: 3,
      isDeleted: false,
      points: [[0, 0], [60, 0]],
      lastCommittedPoint: [60, 0],
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: "arrow",
    },
    // Preprocessing box
    {
      id: "preprocessing",
      type: "rectangle",
      x: 250,
      y: 100,
      width: 120,
      height: 60,
      strokeColor: "#1e1e1e",
      backgroundColor: "#f3e5f5",
      fillStyle: "solid",
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 4,
      version: 1,
      versionNonce: 4,
      isDeleted: false,
    },
    // Preprocessing label
    {
      id: "preprocessing-text",
      type: "text",
      x: 275,
      y: 120,
      width: 70,
      height: 20,
      text: "Preprocessing",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 5,
      version: 1,
      versionNonce: 5,
      isDeleted: false,
    },
    // Arrow 2
    {
      id: "arrow-2",
      type: "arrow",
      x: 370,
      y: 130,
      width: 60,
      height: 0,
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "round",
      seed: 6,
      version: 1,
      versionNonce: 6,
      isDeleted: false,
      points: [[0, 0], [60, 0]],
      lastCommittedPoint: [60, 0],
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: "arrow",
    },
    // LLM Extraction box
    {
      id: "llm-extraction",
      type: "rectangle",
      x: 450,
      y: 100,
      width: 120,
      height: 60,
      strokeColor: "#1e1e1e",
      backgroundColor: "#e8f5e8",
      fillStyle: "solid",
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 7,
      version: 1,
      versionNonce: 7,
      isDeleted: false,
    },
    // LLM Extraction label
    {
      id: "llm-extraction-text",
      type: "text",
      x: 475,
      y: 120,
      width: 70,
      height: 20,
      text: "LLM Extraction",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 8,
      version: 1,
      versionNonce: 8,
      isDeleted: false,
    },
    // Arrow 3
    {
      id: "arrow-3",
      type: "arrow",
      x: 570,
      y: 130,
      width: 60,
      height: 0,
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "round",
      seed: 9,
      version: 1,
      versionNonce: 9,
      isDeleted: false,
      points: [[0, 0], [60, 0]],
      lastCommittedPoint: [60, 0],
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: "arrow",
    },
    // Topic Analysis box
    {
      id: "topic-analysis",
      type: "rectangle",
      x: 650,
      y: 100,
      width: 120,
      height: 60,
      strokeColor: "#1e1e1e",
      backgroundColor: "#fff3e0",
      fillStyle: "solid",
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 10,
      version: 1,
      versionNonce: 10,
      isDeleted: false,
    },
    // Topic Analysis label
    {
      id: "topic-analysis-text",
      type: "text",
      x: 675,
      y: 120,
      width: 70,
      height: 20,
      text: "Topic Analysis",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      groupIds: [],
      strokeSharpness: "sharp",
      seed: 11,
      version: 1,
      versionNonce: 11,
      isDeleted: false,
    },
  ],
  appState: {
    viewBackgroundColor: "#ffffff",
    gridSize: null,
    scrollX: 0,
    scrollY: 0,
    zoom: {
      value: 1,
    },
  },
}; 