{{- if and (eq .Values.workerType "scoring-api") .Values.scoringApi.gateway.enabled .Values.scoringApi.gateway.createGateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "plexus-worker.gatewayName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plexus-worker.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.scoringApi.gateway.gatewayClassName | quote }}
  listeners:
  - name: {{ .Values.scoringApi.gateway.listenerName | quote }}
    protocol: HTTP
    port: {{ .Values.scoringApi.gateway.port }}
    {{- if .Values.scoringApi.gateway.hostname }}
    hostname: {{ .Values.scoringApi.gateway.hostname | quote }}
    {{- end }}
{{- end }}
