optimization:
  max_iterations: 9
  target_accuracy: 0.95
  max_consecutive_no_improvement: 5  # Stop after this many iterations without improvement

model:
  model_type: "gpt-4o-mini-2024-07-18"
  top_p: 0.03
  max_tokens: 2000